version: '3.9'

services:
  database:
    image: postgres:13.9
    environment:
      POSTGRES_USER: blogadmin
      POSTGRES_PASSWORD: blogadmin
      POSTGRES_DB: blog
    networks:
      - backend
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    image: pfeblog-backend:latest
    hostname: backend
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
    networks:
      - web
      - backend
    ports:
      - "8000:8000"
    depends_on:
      - database
  frontend:
    image: pfeblog-frontend:latest
    hostname: frontend
    networks:
      - web
    ports:
      - 3030:3030
    depends_on:
      - backend
  reverse-proxy:
    image: pfeblog-reverse-proxy:latest
    volumes:
      - ./nginx/nginx_default.conf:/etc/nginx/nginx.conf
    ports:
      - "80:8080"
    networks:
      - web
    depends_on:
      - backend
      - frontend

volumes:
  postgres:
networks:
  backend:
  web:

