version: '3.9'

services:
  backend:
    build:
      context: ./django
    image: vps-da62cdaf.vps.ovh.net:8082/pfeblog/backend:latest
    container_name: backend
    hostname: backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./react/blogapi
    image: vps-da62cdaf.vps.ovh.net:8082/pfeblog/frontend:latest
    container_name: frontend
    hostname: frontend
    ports:
      - 3000:3000
