version: '3.9'

services:
  # backend:
  #   build:
  #     context: ./django
  #   image: backend
  #   container_name: backend
  #   hostname: backend
  #   # tty: true
  #   networks:
  #     - web
  #     - backend
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - database
  # frontend:
  #   build:
  #     context: ./react/blogapi
  #   container_name: frontend
  #   hostname: frontend
  #   image: frontend
  #   networks:
  #     - web
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - backend
  database:
    image: postgres:13.9
    environment:
      POSTGRES_USER: blogadmin
      POSTGRES_PASSWORD: blogadmin
      POSTGRES_DB: blog
    networks:
      - backend
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    image: vps-da62cdaf.vps.ovh.net:8082/pfeblog/backend:latest
    container_name: backend
    hostname: backend
    # tty: true
    networks:
      - web
      - backend
    ports:
      - "8000:8000"
    depends_on:
      - database
  frontend:
    image: vps-da62cdaf.vps.ovh.net:8082/pfeblog/frontend:latest
    container_name: frontend
    hostname: frontend
    networks:
      - web
    ports:
      - 3000:3000
    depends_on:
      - backend
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    volumes:
      - ./nginx/nginx_default.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    networks:
      - web
    depends_on:
      - backend

volumes:
  postgres:
networks:
  backend:
  web:

