all:
  children:
    # Individual hosts
    dev1:
      hosts:
        51.75.200.137:

    # Groups hosts : calling hosts defined individually previously
    new_host:
    manager:
      children:
        dev1:
