  # THE APPLY (docker swarm) TASKS ON THE PRODUCTION HOSTS
- hosts: manager 
  # GIVE THE PRIVILEGED PERMISSION TO ANSIBLE
  become: yes 
  # TO NOT COLLECT & DEBUG USELESS DATA (optimize time)
  gather_facts: no 

  vars: 
    # DEFINE THE PYTHON INTERPRETER FOLDER IN THE CONTROLLER NODE
    ansible_python_interpreter: /usr/bin/python3 

  tasks: 
  - name: include vault
    ansible.builtin.include_vars:
      file: vault.yml

  - name: log to private registry
    # USINGE DOCKER LOGIN SSH-CMD FROM "community.docker" MODULE
    # LOGIN TO OUR PRIVATE IMAGE REGISTRY (JFROG)
    docker_login:
      registry: vps-da62cdaf.vps.ovh.net:8082/artifactory/pfeblog/
      username: "{{registry_usr}}"
      password: "{{registry_pwd}}"




  # - name: print variab le
  #   ansible.builtin.debug:
  #     var: vaultmessage



  - name: deploy a stack
    docker_stack:
      state: present
      name: pfeblog
      compose:
        - /home/centos/pfeblog/docker-compose.prod.yml
      with_registry_auth: yes















