- hosts: prod 
  become: yes 
  gather_facts: no 

  vars: 
    ansible_python_interpreter: /usr/bin/python3 

  tasks: 
  - name: log to private registry
    docker_login:
      registry: vps-da62cdaf.vps.ovh.net:8082/artifactory/pfeblog/
      username: gitlab
      password: Gitlab 2023
      # reauthorize: true

  - name: docker-compose down 
    community.docker.docker_compose: 
      project_src: ./pfeblog/
      files:
      - docker-compose.prod.yml
      state: absent 

  - name: pull docker-compose 
    community.docker.docker_compose: 
      project_src: ./pfeblog/
      files:
      - docker-compose.prod.yml
      pull: true
      state: present 

  # - name: build docker-compose 
  #   community.docker.docker_compose: 
  #     project_src: ./pfeblog/
  #     files:
  #     - docker-compose.prod.yml
  #     build: true
  #     state: present 

  # - name: run docker-compose 
  #   community.docker.docker_compose: 
  #     project_src: ./pfeblog/
  #     files:
  #     - docker-compose.prod.yml
 