- hosts: prod 
  become: yes 
  gather_facts: no 

  vars: 
    ansible_python_interpreter: /usr/bin/python3 

  tasks: 
    - name: copy docker-compose.yml 
      copy: 
        src: ./docker-compose.prod.yml 
        dest: . 

#    - name: test docker-compose 
#      community.docker.docker_compose: 
#        project_src: ./compose/ 
#        state: present 

 

 