  # THE APPLY TASKS ON THE PRODUCTION HOSTS
- hosts: prod 
  # GIVE THE PRIVILEGED PERMISSION TO ANSIBLE
  become: yes 
  # TO NOT COLLECT & DEBUG USELESS DATA (optimize time)
  gather_facts: no 

  vars: 
    # DEFINE THE PYTHON INTERPRETER FOLDER IN THE CONTROLLER NODE
    ansible_python_interpreter: /usr/bin/python3 

  tasks: 
  - name: log to private registry
    # USINGE DOCKER LOGIN SSh-CMD from "community.docker" MODULE
    # Login to our private registry
    docker_login:
      registry: vps-da62cdaf.vps.ovh.net:8082/artifactory/pfeblog/
      ###################################################
      # THIS DATA MUST BE HIDDEN BY USING ANSIBLE VAULT #
      username: gitlab
      password: Gitlab 2023
      ###################################################

  - name: docker-compose down 
    # USINGE DOCKER COMPOSE SSh-CMD from "community.docker" MODULE
    community.docker.docker_compose: 
      project_src: ./pfeblog/
      files:
      - docker-compose.prod.yml
      # Turn down all Docker Compose services
      state: absent 

  - name: pull docker-compose 
    # USINGE DOCKER COMPOSE SSh-CMD from "community.docker" MODULE
    community.docker.docker_compose: 
      project_src: ./pfeblog/
      files:
      - docker-compose.prod.yml
      # Pull services images from our PR 
      pull: true
      # Turn on all Docker Compose services
      state: present 

 