- hosts: prod 
  become: yes 
  gather_facts: no 

  vars: 
    ansible_python_interpreter: /usr/bin/python3 

  tasks: 
  - name: log to private registry
    docker_login:
      registry: 51.75.202.237:8082/artifactory/pfeblog/
      username: gitlab
      password: JFrog@dmin2023

  # - name: test docker-compose 
  #   community.docker.docker_compose: 
  #     project_src: ./compose/ 
  #     state: present 

 

 