all:
  children:
    manager:
      hosts:
        192.168.28.145  #docker swarm manager
  # Older setting (below)
        # host-1:
        #   ansible_host: 192.168.28.145  #docker swarm manager
        #   ansible_user: hanane
        #   ansible_password: hanane

