  # THIS PLAYBOOK COMMANDS THE DOCKER SWARM MANAGER NODE TO APPLY
  # THE STACK FILE ("docker-compose.prod.yml") COPIED BY THE 
  # "play.copyfiles.yml" PLAYBOOK ON THE WORKER NODES
  ### ---
  # THE EXECUTION OF THIS PLAYBOOK REQUIRES 
- hosts: manager 
  # GIVE THE PRIVILEGED PERMISSION TO ANSIBLE
  become: yes 
  # TO NOT COLLECT & DEBUG USELESS DATA (optimize time)
  gather_facts: no 

  vars: 
    # DEFINE THE PYTHON INTERPRETER FOLDER IN THE CONTROLLER NODE OF ANSIBLE
    ansible_python_interpreter: /usr/bin/python3 

  tasks: 
    # THIS TASK DECRYPTS AND LOADS VARIABLES THAT ARE STORED IN VAULT FILE
    # THE VAULT FILE IS CALLED "vault.yml" WE MENTIONNED IT BY THE ATTRIBUT "file" 
  - name: include vault
    ansible.builtin.include_vars:
      file: vault.yml

  - name: log to private registry
    # USINGE DOCKER LOGIN SSH-CMD FROM "community.docker" MODULE
    # LOGIN TO OUR PRIVATE IMAGE REGISTRY (JFROG)
    docker_login:
      registry: vps-da62cdaf.vps.ovh.net:8082/artifactory/pfeblog/
      username: "{{registry_usr}}"
      password: "{{registry_pwd}}"

  - name: deploy a stack
    # USING DOCKER STACK MODULE TO RUN A DOCKER COMPOSE AS A DOCKER STACK
    # FOR DOCKER SWARM CLUSTER
    docker_stack:
      state: present
      # GIVE THE SWARM STACK A NAME ("pfeblog")
      name: pfeblog
      compose:
        - /home/centos/pfeblog/docker-compose.prod.yml
      with_registry_auth: yes















